# Generated by Django 3.2.3 on 2021-07-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
